Feature/declare nodes
aaronpeikert/StenoGraphs.jl pull request #57
Opened 2024-03-15 15:09 UTC by aaronpeikert

This PR introduces a new system that allow explicitly declaring nodes, while still requiring very little typing.

2024-03-18 21:38 UTC, Maximilian-Stefan-Ernst requested changes
Looks great, I just added some small suggestions.
Maybe it would also be nice to have a doc page that shows these new macros in use with an example.

2024-03-18 21:38 UTC, Maximilian-Stefan-Ernst commented on docs/Manifest.toml
I think you could stop tracking the manifest file with git - package repositories don't really do this, and it gives you large, meaningless diffs

2024-03-18 21:38 UTC, Maximilian-Stefan-Ernst commented on src/syntax/macro.jl
> +Takes a vector of arrows and turns these into a list of edges.
```suggestion
Takes a vector of arrows and turns it into a vector of edges.
```

2024-03-18 21:38 UTC, Maximilian-Stefan-Ernst commented on src/syntax/macro.jl
> +For programatic use see also [`@declare_nodes_from`](@ref).
```suggestion
For programmatic use see also [`@declare_nodes_from`](@ref).
```

2024-03-18 21:38 UTC, Maximilian-Stefan-Ernst commented on src/syntax/macro.jl
> +    @declare_nodes(x::Vector{ <: Arrow})
I don't know how macros are typically documented, but maybe something like this (BenchmarkTools does it similarly):
```suggestion
    @declare_nodes <node names>
```

2024-03-18 21:38 UTC, Maximilian-Stefan-Ernst commented on src/syntax/macro.jl
> +    @declare_nodes(x::Vector{ <: Arrow})
```suggestion
    @declare_nodes_from <x::Vector{Symbol}>
```

2024-03-18 21:38 UTC, Maximilian-Stefan-Ernst commented on src/syntax/macro.jl
> +@declare_nodes_from(nodes)
```suggestion
@declare_nodes_from nodes
```

2024-03-18 21:38 UTC, Maximilian-Stefan-Ernst commented on test/macro.jl
> +    @declare_nodes_from(nodes)
```suggestion
    @declare_nodes_from nodes
```

2024-03-18 21:38 UTC, Maximilian-Stefan-Ernst commented on test/macro.jl
> +    nodes = [Symbol(i) for i in "xyz"]
```suggestion
    nodes = Symbol.(["x", "y", "z"])
```

2024-03-18 21:38 UTC, Maximilian-Stefan-Ernst commented on src/syntax/macro.jl
> +nodes = [Symbol(i) for i in ('a':'e')]
```suggestion
nodes = Symbol.('a':'e')
```

2024-03-19 14:54 UTC, aaronpeikert commented on docs/Manifest.toml
Packages should not track manifests, since they are expected to work with all package versions. This however is the manifest from which the documentation is build, so I'll keep it.

2024-04-03 06:36 UTC, merged